project_id = "lohucijybvchcqqqwlmk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[functions.discord-sync]
verify_jwt = false

[functions.telegram-integration]
verify_jwt = false

[functions.hunter-io]
verify_jwt = true

[functions.virustotal]
verify_jwt = true

[functions.verify-captcha]
verify_jwt = false