// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhuaseazgakcynkbciof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpodWFzZWF6Z2FrY3lua2JjaW9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTI0ODksImV4cCI6MjA3MTQ2ODQ4OX0._Gvyydt70_iHGMfu5SP0hH0eX8Da59ZPcLqPUUoWgO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});